services:
  - type: web
    name: whatsapp-socketio
    runtime: node
    buildCommand: npm install
    startCommand: node server.js
    env: node
    envVars:
      - key: PORT
        value: 3000
      - key: NODE_ENV
        value: production
